services:
  - docker
before_install:
  - ./wait.sh
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-all.txt
script:
  - cd tests && python -m pytest --cov=pysirix
