dist: focal
services:
  - docker
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
before_install:
  - bash ./test.sh
install:
  - pip install -r requirements-all.txt
script:
  - python -m pytest --cov=pysirix -v
