services:
  - docker
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-all.txt
script:
  - bash ./test.sh && docker-compose -f ./tests/resources/docker-compose.yml logs
  - cd tests && python -m pytest --cov=pysirix
