dist: bionic
services:
  - docker
language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - bash ./test.sh
install:
  - pip install -r requirements-all.txt
script:
  - cd tests && python -m pytest --cov=pysirix
